[package]
name = "modgeosys_nav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maturin = "1.5.1"
ndarray = "0.15.6"
ordered-float = "4.2.0"
pyo3 = "0.20.3"
