select = ["ALL"]

# Ignore some rules.
ignore = [
    "ANN001",   # Missing type annotation for 'self' in method
    "ANN002",   # Missing type annotation for 'cls' in method
    "ANN101",   # Missing type annotation for 'self' in method
    "ANN204",   # Missing return type annotation for special method
    "ANN401",   # Dynamically typed expressions (typing.Any) are disallowed
    "D105",     # Missing docstring in magic method
    "D107",     # Missing docstring in '__init__'
    "D202",     # No blank lines allowed after function docstring
    "D203",     # 1 blank line required before class docstring
    "D204",     # 1 blank line required after class docstring
    "D208",     # Docstring is over-indented
    "D209",     # Multi-line docstring closing quotes should be on a separate line
    "D213",     # Multi-line docstring summary should start at the second line
    "E501",     # Line too long ({width} > {limit} characters)
    "FA100",    # Missing 'from __future__ import annotations', but uses `{name}`
    "FA102",    # Missing 'from __future__ import annotations', but uses
    "I001",     # Import block is un-sorted or un-formatted
    "PLR0911",  # Too many return statements ({returns} > {max_returns})
    "Q000",     # Single quotes found but double quotes preferred
    "S101",     # Use of assert detected.
]
